### ISSUE TITLE
Is it possible to capture only the current screen?

### ISSUE THREAD

**Issue by ironynet** [myflashlab/webView-ANE#137]
I know that 'requestBitmap()' capture the whole area of the richwebview.
Is it possible to capture only the visible area (or only a specific area)?
Sometimes when capturing the whole area is app crash by OutOfMemoryError .

[logcat]
Throwing OutOfMemoryError "Failed to allocate a 123249612 byte allocation with 16777120 free bytes and 102MB until OOM"
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                   Process: air.com.doitflash.exWebView, PID: 26567
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 123249612 byte allocation with 16777120 free bytes and 102MB until OOM
                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                       at android.graphics.Bitmap.nativeCreate(Native Method)
                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                       at com.doitflash.webView.AirCommand$TakeAshot.doInBackground(AirCommand.java:1056)
                                                       at com.doitflash.webView.AirCommand$TakeAshot.doInBackground(AirCommand.java:1043)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818) 

--------------------------------------------------------------------------------------------------------------------

thanks.

**Comment by myflashlab** [comment]
Supporting the current view screenshot is in our to-do list. I have just marked this issue and you'll be updated as soon as this feature is added. I am not able to tell you when exactly but it's in our to-do list.

About the ```OutOfMemoryError``` I think that happens when your webpage is too large! which makes sense. Have you seen that error on smaller webpages also?

**Comment by ironynet** [comment]
yes. 'OutOfMemoryError' is when the web page is too big. There is no problem with small-sized web pages. Thank you for your reply and I will be waiting for a version with added features.

**Comment by syberkitten** [comment]
Having the same issue, It happened with the Demo app actually,
when scaling the webview to something larger the 120% the app crashes.

I'm about to the test it in my real app, will let know.

**Comment by syberkitten** [comment]
Ok, bad news ... 
It happens in my app as well, scaling the webview above 150% crashes
the whole app.

As a workaround, is it possible in some fashion to limit the maximum scale of the webview?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
