### ISSUE TITLE
Build faild in FlashDevelop

### ISSUE THREAD

**Issue by jibon57** [myflashlab/webView-ANE#180]
Hello,

I am new here. I am trying to compile the package but getting this error:

```
Packaging and installing application for captive use on Android (192.168.56.1)

Packaging: dist\theApp-captive-runtime.apk
using certificate: cert\myflashlabs.p12...

dx tool failed:

APK setup creation FAILED.

Troubleshooting:
- verify AIR SDK target version in application.xml

Press any key to continue . . .

```
application.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>com.doitflash.exWebView</id>
  <versionNumber>7.1.0</versionNumber>
  <supportedProfiles>mobileDevice</supportedProfiles>
  <filename>exWebView</filename>
  <name>Rich Webview</name>
  <android>
    <manifestAdditions>
		<![CDATA[<manifest android:installLocation="auto">
		<uses-permission android:name="android.permission.WAKE_LOCK" />
		<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
			
		<!--The new Permission thing on Android works ONLY if you are targetting Android SDK 23 or higher-->
		<uses-sdk android:targetSdkVersion="23"/>
		
		<!--required for enabling gps for webview-->
		<uses-permission android:name="android.permission.INTERNET" />
		<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
		
		<application android:hardwareAccelerated="true" android:allowBackup="true">
			<activity android:hardwareAccelerated="true">
				<intent-filter>
					<action android:name="android.intent.action.MAIN" />
					<category android:name="android.intent.category.LAUNCHER" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.VIEW" />
					<category android:name="android.intent.category.BROWSABLE" />
					<category android:name="android.intent.category.DEFAULT" />
				</intent-filter>
			</activity>
			
			<!-- required for html file select buttons -->
			<activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" />
			
			<receiver android:name="com.doitflash.webView.ChromeTabActionBroadcastReceiver" />
			
		</application>
		
</manifest>]]></manifestAdditions>
  </android>
  <iPhone>
    <!--https://developer.apple.com/library/ios/documentation/general/reference/infoplistkeyreference/Articles/iPhoneOSKeys.html-->
    <!--http://help.adobe.com/en_US/air/build/WSfffb011ac560372f7e64a7f12cd2dd1867-8000.html-->
    <!-- A list of plist key/value pairs to be added to the application Info.plist -->
    <InfoAdditions>
		<![CDATA[
		
			<key>MinimumOSVersion</key>
			<string>8.0</string>
			
			<key>UIStatusBarStyle</key>
			<string>UIStatusBarStyleBlackOpaque</string>
			
			<key>UIRequiresPersistentWiFi</key>
			<string>NO</string>
			
			<key>UIPrerenderedIcon</key>
			<true />
			
			<key>NSAppTransportSecurity</key>  
			<dict>  
				<key>NSAllowsArbitraryLoads</key><true/>  
			</dict>
			
			<!--required for webview GPS access-->
			<key>NSLocationUsageDescription</key>
			<string>I need location 1</string>
			
			<key>NSLocationWhenInUseUsageDescription</key>
			<string>I need location 2</string>
			
			<key>NSLocationAlwaysUsageDescription</key>
			<string>I need location 3</string>
		
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
			
		]]></InfoAdditions>
		
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  <initialWindow>
    <title>exWebView</title>
    <content>ex.swf</content>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <autoOrients>true</autoOrients>
    <!--<aspectRatio>portrait</aspectRatio>-->
    <renderMode>direct</renderMode>
    <!--<depthAndStencil>true</depthAndStencil>-->
    <!-- required for 3D -->
    <systemChrome>standard</systemChrome>
  </initialWindow>
  <icon>
    <image48x48>icons/icon_48.png</image48x48>
    <image57x57>icons/icon_57.png</image57x57>
    <image72x72>icons/icon_72.png</image72x72>
    <image76x76>icons/icon_76.png</image76x76>
    <image96x96>icons/icon_96.png</image96x96>
    <image114x114>icons/icon_114.png</image114x114>
    <image120x120>icons/icon_120.png</image120x120>
    <image144x144>icons/icon_144.png</image144x144>
    <image152x152>icons/icon_152.png</image152x152>
    <!--<image512x512>icons/icon_512.png</image512x512>-->
  </icon>
  <extensions>
	
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
	
	<!-- Required if you are targetting AIR 24+ and have to take care of Permissions mannually -->
	<extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
	
	<!-- download the dependency ANEs from https://github.com/myflashlab/common-dependencies-ANE -->
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
	
  </extensions>
</application>
```

In where I am doing wrong?

Thanks

**Comment by jibon57** [comment]
OK, I have downloaded Flex 4.6.0 + AIR 24 SDK. But now getting following error:

```
'.\..\..\..\SDK.bat' is not recognized as an internal or external command,
operable program or batch file.

Packaging and installing application for captive use on Android (192.168.56.1)

Packaging: dist\theApp-captive-runtime.apk
using certificate: cert\myflashlabs.p12...

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$anim;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:737)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:637)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
        at com.android.dx.command.dexer.Main.run(Main.java:247)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting


APK setup creation FAILED.

Troubleshooting:
- verify AIR SDK target version in application.xml
```

**Comment by myflashlab** [comment]
Well, you should be inspired by the demo project. the error messages you are experiencing is because you are trying to run the demo project directly. instead of that, build your own project with your own certificate .p12 file and use the latest AIR SDK, for example 26.0 and then be inspired by the sample project. That should help you.

**Comment by jibon57** [comment]
@myflashlab Thanks for reply. Can you send me one working demo project? I want to test as I said that I am new here. I was quickly trying like this:

```
<?xml version="1.0" encoding="utf-8"?>
<s:View xmlns:fx="http://ns.adobe.com/mxml/2009" 
		xmlns:s="library://ns.adobe.com/flex/spark" title="HomeView">
	<fx:Script>
			<![CDATA[
				
				import flash.net.URLRequest;
				import flash.net.navigateToURL;
				import flash.display.MovieClip;
				import flash.media.StageWebView;
				import flash.geom.Rectangle;
				import flash.events.KeyboardEvent;
				import flash.ui.Keyboard;
				import flash.desktop.NativeApplication;
				import mx.events.FlexEvent; 
				import com.myflashlab.air.extensions.webView.RichWebView;
				import com.myflashlab.air.extensions.webView.RichWebViewEvent;
				import com.myflashlab.air.extensions.webView.RichWebViewSettings;
				
				private var browser:StageWebView;
				private var _ex:RichWebView;
				
				protected function onButtonClicked(event:MouseEvent):void
				{
					//browser = new StageWebView();
					//browser.stage = this.stage;
					//browser.viewPort = new Rectangle( 0, 0, this.stage.stageWidth, this.stage.stageHeight);
					//browser.loadURL("https://cnpro1.rosettastone.cn");
					_ex = new RichWebView();
					
					_ex.openWebViewURL(0, 0, stage.stageWidth, stage.stageHeight, "https://cnpro1.rosettastone.cn/");
				}       
				
			]]>
		</fx:Script>
		
		<s:Button x="209" y="300" label="Start" click="onButtonClicked(event)" />
</s:View>
```
StageWebView was working just fine but not with RichWebView. I am getting this error:

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.webView.android::Android()
	at com.myflashlab.air.extensions.webView::RichWebView()
	at views::testHomeView/onButtonClicked()[D:\Others\Adobe Flash Builder 4.6\test\src\views\testHomeView.mxml:32]
	at views::testHomeView/___testHomeView_Button1_click()[D:\Others\Adobe Flash Builder 4.6\test\src\views\testHomeView.mxml:40]
```
Please give me suggestion. Thanks in advance :)

**Comment by jibon57** [comment]
@myflashlab I have tried this but wasn't successful. I have uploaded it here:
 https://github.com/jibon57/webView-ANE-issue
Please have a look.

**Comment by jibon57** [comment]
I missed to include this in application.xml

`<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>`
