### ISSUE TITLE
hide and requestBitmap crash app

### ISSUE THREAD

**Issue by 4malik** [myflashlab/webView-ANE#194]
Hi.

When i need to show something under webview i'm calling
```javascript
static public function hide():void {
	addEventListenersToWeb(false);
	trace("hide:addEventListener");
	mWeb.addEventListener(RichWebViewEvent.SCREENSHOT, web_eventHandler);
	trace("hide:requestBitmap");
	mWeb.requestBitmap();
	mWeb.hide(true);
}
```
and when i need to show webview again
```javascript
static public function show():void {
	addEventListenersToWeb(true);
	trace("show:removeEventListener");
	mWeb.removeEventListener(RichWebViewEvent.SCREENSHOT, web_eventHandler);
	mWeb.hide(false);
}

```

Event Handler
```javascript
static private function web_eventHandler(event:RichWebViewEvent):void {
	if (event.type == RichWebViewEvent.SCREENSHOT) {
		trace("web_eventHandler:SCREENSHOT" + event.param);
		var bm:Bitmap = new Bitmap(event.param, "auto", true);
	}
}
```
when i call hide and show with some little delay i got crash. so in logs i got next in output:
```javascript
hide:addEventListener
hide:requestBitmap
web_eventHandler:SCREENSHOT[object BitmapData]
show:removeEventListener
hide:addEventListener
hide:requestBitmap
```

so i watched that crash in logcat
```javascript
12-02 21:40:54.423 30344 30344 I air.com.elimotoday.test: hideMap:addEventListener
12-02 21:40:54.423 30344 30344 I air.com.elimotoday.test: hideMap:requestBitmap
12-02 21:40:54.727 30344 30359 I art     : Background sticky concurrent mark sweep GC freed 94346(7MB) AllocSpace objects, 26(800KB) LOS objects, 17% free, 34MB/41MB, paused 11.944ms total 69.605ms
12-02 21:40:55.573 30344 30344 I air.com.elimotoday.test: web_eventHandler:SCREENSHOT[object BitmapData]
12-02 21:40:55.681 30344 30344 I air.com.elimotoday.test: showMap:removeEventListener
12-02 21:40:56.248 30344 30344 I air.com.elimotoday.test: hideMap:addEventListener
12-02 21:40:56.249 30344 30344 I air.com.elimotoday.test: hideMap:requestBitmap
12-02 21:40:56.556 30344 30344 D AndroidRuntime: Shutting down VM
12-02 21:40:56.558 30344 30344 E AndroidRuntime: FATAL EXCEPTION: main
12-02 21:40:56.558 30344 30344 E AndroidRuntime: Process: air.com.elimotoday.test, PID: 30344
12-02 21:40:56.558 30344 30344 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at com.doitflash.webView.AirCommand$TakeAshot.onPostExecute(AirCommand.java:1396)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at com.doitflash.webView.AirCommand$TakeAshot.onPostExecute(AirCommand.java:1340)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:651)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at android.os.AsyncTask.access$500(AsyncTask.java:180)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:234)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5526)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-02 21:40:56.558 30344 30344 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-02 21:40:56.562   994  3177 D ActivityManager: New dropbox entry: air.com.elimotoday.test, data_app_crash, 16e9432a-f152-433c-8246-a7994efe670f
12-02 21:40:56.565   994  3177 W ActivityManager:   Force finishing activity air.com.elimotoday.test/.AppEntry
```

I think that happens cause map is not showed in a moment i called requestBitmap. So it needs some fixes. Functions hide and show can be called by different events. So this error can be easily reproduced  by users and that is really bad.

By the way you can see that 2nd hide(that crashed app) i called after i got bitmap from 1st call.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
